// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc4L7j_i9O9901LMWdhfji3VSKqjUeTes',
    appId: '1:747516182629:android:4b6c8c6f85bf9fc53a868c',
    messagingSenderId: '747516182629',
    projectId: 'masraftakipuygulamasi',
    storageBucket: 'masraftakipuygulamasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI3Cn0merqQcfi8-_EGqAGAFNJqMSFRFs',
    appId: '1:747516182629:ios:1e16e637f0ef86533a868c',
    messagingSenderId: '747516182629',
    projectId: 'masraftakipuygulamasi',
    storageBucket: 'masraftakipuygulamasi.firebasestorage.app',
    iosBundleId: 'com.expensetracker.app.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI3Cn0merqQcfi8-_EGqAGAFNJqMSFRFs',
    appId: '1:747516182629:ios:1e16e637f0ef86533a868c',
    messagingSenderId: '747516182629',
    projectId: 'masraftakipuygulamasi',
    storageBucket: 'masraftakipuygulamasi.firebasestorage.app',
    iosBundleId: 'com.expensetracker.app.expenseTrackerApp',
  );
}
